// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXq6R_p8NctDHdr0Z2mgIj1rxqgR5OcGM',
    appId: '1:867476070936:web:3eba482067f23e3509596d',
    messagingSenderId: '867476070936',
    projectId: 'recicla-the-ifpi',
    authDomain: 'recicla-the-ifpi.firebaseapp.com',
    databaseURL: 'https://recicla-the-ifpi-default-rtdb.firebaseio.com',
    storageBucket: 'recicla-the-ifpi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPe6OV698Hzeq9saEfx6_cyyXXIm4vS8E',
    appId: '1:867476070936:android:55f65a1bb8a16ad709596d',
    messagingSenderId: '867476070936',
    projectId: 'recicla-the-ifpi',
    databaseURL: 'https://recicla-the-ifpi-default-rtdb.firebaseio.com',
    storageBucket: 'recicla-the-ifpi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLsxg3moenaZJkG6nTuD98oiCOSxSN6s',
    appId: '1:867476070936:ios:e24bfab13e614cec09596d',
    messagingSenderId: '867476070936',
    projectId: 'recicla-the-ifpi',
    databaseURL: 'https://recicla-the-ifpi-default-rtdb.firebaseio.com',
    storageBucket: 'recicla-the-ifpi.firebasestorage.app',
    iosBundleId: 'com.example.reciclaThe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLsxg3moenaZJkG6nTuD98oiCOSxSN6s',
    appId: '1:867476070936:ios:e24bfab13e614cec09596d',
    messagingSenderId: '867476070936',
    projectId: 'recicla-the-ifpi',
    databaseURL: 'https://recicla-the-ifpi-default-rtdb.firebaseio.com',
    storageBucket: 'recicla-the-ifpi.firebasestorage.app',
    iosBundleId: 'com.example.reciclaThe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXq6R_p8NctDHdr0Z2mgIj1rxqgR5OcGM',
    appId: '1:867476070936:web:84e4c2edfa07ce0309596d',
    messagingSenderId: '867476070936',
    projectId: 'recicla-the-ifpi',
    authDomain: 'recicla-the-ifpi.firebaseapp.com',
    databaseURL: 'https://recicla-the-ifpi-default-rtdb.firebaseio.com',
    storageBucket: 'recicla-the-ifpi.firebasestorage.app',
  );

}